# Generated by Django 3.0.4 on 2020-03-07 11:50
import django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="summary",
            options={"ordering": ["-created"], "verbose_name_plural": "Summaries"},
        ),
        migrations.RenameField(
            model_name="summary", old_name="original_data", new_name="raw_data",
        ),
        migrations.AddField(
            model_name="summary",
            name="countries_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
