# Generated by Django 3.0.4 on 2020-03-07 14:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_auto_20200307_1250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="countries_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
