# Generated by Django 3.0.4 on 2020-03-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_auto_20200307_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary", name="confirmed", field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="summary", name="deaths", field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="summary", name="recovered", field=models.PositiveIntegerField(),
        ),
    ]
