# Generated by Django 3.0.4 on 2020-03-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_switch_to_positive_integers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="summary", old_name="countries_data", new_name="regions_data",
        ),
    ]
