# Generated by Django 3.0.4 on 2020-03-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_rename_country_to_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="is_latest_for_day",
            field=models.BooleanField(default=False),
        ),
    ]
